const Discord = require("discord.js");

module.exports.run = async (bot, message, args) => {
  liste=[
    `BaDumTss`,
    `YouDied`,
    `Cena`,
    `FuckYou`,
    `KO`,
    `Explosion`,
    `Popopo`,
    `Oof`,
    `Maneuver`,
    `OfCourse`,
    `Yes`,
    `Ya`,
    `E`,
    `Clap`,
    `Sparta`,
    `Hey`,
    `Facepalm`,
    `ZaWarudo`,
    `Muda`,
    `Noice`,
    `No`,
    `SadViolin`,
    `Brainpower`,
    `Drama`,
    `What`,
    `Tuturu`,
    `Wow`,
    `Omae`,
    `Trombone`,
    `Crabrave`,
    `Succ`,
    `Okay`,
    `Woah`,
    `Honte`,
    `Roar`,
    `Continued`,
    `Shit`,
    `Wednesday`,
    `Gay`,
    `Wasted`,
    `WeGotHim`,
    `Mine`,
    `Gotcha`,
    `Windows`,
    `Thot`,
    `Jazz`,
    `RightBack`,
    `Projet`,
    `AH`,
    `Moments`,
    `Inches`,
    `Eternity`,
    `Slow`,
    `Cry`,
    `Aah`,
    `Thicc`,
    `DeusVult`,
    `Mielpops`,
    `Chocapic`,
    `Jack`,
    `Mimes`,
    `Duel`,
    `Bluff`,
    `Vous`,
    `Chips`,
    `TwoWays`,
    `Damage`,
    `Ganon`,
    `Squalala`,
    `Jeanne`,
    `TG`,
    `Con`,
    `Prophecy`,
    `Sax`,
    `Philippe`,
    `Mechant`,
    `Coda`,
    `Run`,
    `HeKnew`,
    `DGE`,
    `XFiles`,
    `AYAYAYA`,
    `Ayaya`,
    `AAA`,
    `DrumRoll`,
    `IlSuffit`,
    `Decide`
  ]
  liste.sort();
  messageToSend = "";
  for(i = 0; i < liste.length;i++){
    messageToSend += "`" + liste[i] + "` ";
  }
  return message.reply("Les effets sonores disponibles sont au nombre de " + liste.length + " et sont " + messageToSend);
}

module.exports.help = {
  name: "listSE",
  type: "social", //social fun Private ou admin
  usage: "listSE",
  desc: "j'envoit la liste des effets sonores disponibles"
}
